### ISSUE TITLE
Rendering fails - 'Vertex shader failed to compile' 

### ISSUE THREAD

**Issue by JeanneKahn** [CesiumGS/cesium-workshop#22]
Installed the workshop to see if I can use it for teaching Cesium, but found this error when starting up from both `npm` and `python`: 

```
An error occurred while rendering. Rendering has stopped.
RuntimeError: Vertex shader failed to compile.  Compile log: ERROR: 0:50: 'w' : vector field selection out of range

Error
    at new HS (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:77:4591)
    at $Se (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:896:122)
    at gQ (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:897:1409)
    at H3 (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:897:1361)
    at zm._bind (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:897:2210)
    at NQe (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:8352:41422)
    at Au.draw (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:8352:42192)
    at kv.execute (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:894:36194)
    at Ca (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:11738:17586)
    at UY (https://cesium.com/downloads/cesiumjs/releases/1.103/Build/Cesium/Cesium.js:11738:22446)
```

Console errors also included. 
[console error.txt](https://github.com/CesiumGS/cesium-workshop/files/11013078/console.error.txt)

I am on Kubuntu 22.04. I tried installing WebGL drivers to fix this, but it didn't (and Cesium works in general for me as well, so it's not something across every Cesium application)

**Comment by JeanneKahn** [comment]
I've figured out that if you rename the `CesiumDrone.gltf` file, this error doesn't happen. I suspect something is wrong with the model provided.

**Comment by houluy** [comment]
@JoshuaKahn I got the same error message. How did you fix it?
